<?php 
include_once'DAO.inc.php';
require_once'DAO/activiteDAO.inc.php';
require_once'DAO/articlesDAO.inc.php';
require_once'DAO/biographieDAO.inc.php';
require_once'DAO/gradeDAO.inc.php';
require_once'DAO/joursemaineDAO.inc.php';
require_once'DAO/languesDAO.inc.php';
require_once'DAO/main_settingsDAO.inc.php';
require_once'DAO/membreDAO.inc.php';
require_once'DAO/planningDAO.inc.php';
require_once'DAO/prestationDAO.inc.php';
require_once'DAO/rel_planning_joursemaineDAO.inc.php';
require_once'DAO/reseauxsociauxDAO.inc.php';
require_once'DAO/sponsorDAO.inc.php';
require_once'DAO/menuDAO.inc.php';
?>