<?php 
include_once'DAO.inc.php';
require_once'activiteDAO.inc.php';
require_once'articlesDAO.inc.php';
require_once'biographieDAO.inc.php';
require_once'gradeDAO.inc.php';
require_once'joursemaineDAO.inc.php';
require_once'languesDAO.inc.php';
require_once'main_settingsDAO.inc.php';
require_once'membreDAO.inc.php';
require_once'planningDAO.inc.php';
require_once'prestationDAO.inc.php';
require_once'rel_planning_joursemaineDAO.inc.php';
require_once'reseauxsociauxDAO.inc.php';
require_once'sponsorDAO.inc.php';
?>